### ISSUE TITLE
mvn package wrong

### ISSUE THREAD

**Issue by ghost** [Activiti/Activiti-Designer#46]
####  i checked activiti-designer-5.18.0 tag and mvn package wrong,it seems that the http://download.eclipse.org/graphiti/updates/0.11.4. can't found.how can i resolve this.The console is below:

➜  Activiti-Designer-activiti-designer-5.18.0 mvn package
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.activiti.designer:org.activiti.designer.libs:5.18.0-SNAPSHOT @ /Users/qk/Downloads/Activiti-Designer-activiti-designer-5.18.0/org.activiti.designer.libs/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/releases/luna
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201406250900/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201409261001/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201501121000/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/luna/201502271000/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/graphiti/updates/0.11.4
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'Graphiti' from location http://download.eclipse.org/graphiti/updates/0.11.4: No repository found at http://download.eclipse.org/graphiti/updates/0.11.4. -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'Graphiti' from location http://download.eclipse.org/graphiti/updates/0.11.4
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'Graphiti' from location http://download.eclipse.org/graphiti/updates/0.11.4
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:301)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits(TargetPlatformFactoryImpl.java:269)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:174)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:126)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
	at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:82)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:221)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:77)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	... 11 more
Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://download.eclipse.org/graphiti/updates/0.11.4.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:692)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:59)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:52)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:297)
	... 22 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by rohitbatta** [comment]
You can change pom.xml file from following location. 

file name is:  **/Activiti-Designer-master/org.activiti.designer.parent/pom.xml** and change line from
 
```
<graphiti-site>http://download.eclipse.org/graphiti/updates/0.11.4</graphiti-site> to
<graphiti-site>http://archive.eclipse.org/graphiti/updates/0.11.4</graphiti-site>
```

This is because, eclipse has changed it's graphiti images location from download.eclipse.org to archive.eclipse.org.

**Comment by ghost** [comment]
### thanks. it packaged successful and i shared the result [org.activiti.designer.updatesite-5.18.1-SNAPSHOT.zip](http://pan.baidu.com/s/1i4TLUS1)

  [INFO] Activiti Designer - Parent project ................. SUCCESS [  0.002 s]
[INFO] Activiti Designer - Libs ........................... SUCCESS [04:33 min]
[INFO] Activiti Designer - Integration .................... SUCCESS [  0.587 s]
[INFO] Activiti Designer - Util ........................... SUCCESS [  0.520 s]
[INFO] Activiti Designer - Eclipse ........................ SUCCESS [  0.681 s]
[INFO] Activiti Designer - GUI ............................ SUCCESS [  1.013 s]
[INFO] Activiti Designer - Help ........................... SUCCESS [  0.075 s]
[INFO] Activiti Designer - Validate BPMN 2.0 .............. SUCCESS [  0.290 s]
[INFO] Activiti Designer - Util ........................... SUCCESS [  0.165 s]
[INFO] Activiti Designer - Kickstart - Eclipse ............ SUCCESS [  2.191 s]
[INFO] Activiti Designer - Kickstart - Forms .............. SUCCESS [  0.380 s]
[INFO] Activiti Designer - Kickstart - Process ............ SUCCESS [  0.375 s]
[INFO] Activiti Designer - Feature ........................ SUCCESS [  0.097 s]
[INFO] Activiti Designer - Update site .................... SUCCESS [  2.683 s]
[INFO] Activiti Designer - Root project ................... SUCCESS [  0.000 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36:33 min
[INFO] Finished at: 2016-12-28T20:14:28+08:00
[INFO] Final Memory: 158M/1213M
[INFO] ------------------------------------------------------------------------
➜  Activiti-Designer-master pwd
